valor = float(input("Qual o valor da hora trabalhada? "))
horas = float(input("Quantas horas foram trabalhadas? "))
salario_bruto = (valor * horas)
ir = (salario_bruto * 0.11)
inss = (salario_bruto * 0.08)
sindicato = (salario_bruto * 0.05)
salario_liquido = (salario_bruto - ir - inss - sindicato)
print("salario bruto de ", salario_bruto)
print("IR (11%):",ir )
print("INSS (8%):", inss)
print("Sindicato (5%): ", sindicato )
print("Salario liquido: ", salario_liquido)